---
- name: Install OpenShift 4 with CRC
  hosts: all
  tasks:
    - name: Set architecture for MacOS
      set_fact:
        crc_download_name: "crc-macos-amd64"

    - name: Set crc version
      set_fact:
        crc_version: "crc-macos-1.0.0-beta.3-amd64"

    - name: Set variable crc_tar_name
      debug: msg="/tmp/{{ crc_download_name }}.tar.xz"
      register: crc_tar_name

    - name: Set variable crc_dir_name
      debug: msg="{{ ansible_env.HOME }}/{{ crc_version }}"
      register: crc_dir_name

    - name: Check if the latest CRC software exists
      stat:
        path: '{{ crc_tar_name.msg }}'
      register: file_details
    - name: Check if directory with CRC software exists.
      stat:
        path: '{{ crc_dir_name.msg }}'
      register: dir_details

    - name: Check if crc binary exist
      stat:
        path: /usr/local/bin/crc
      register: crc_binary

    - name: Get the latest CRC software
      get_url:
        url: 'https://mirror.openshift.com/pub/openshift-v4/clients/crc/latest/{{ crc_download_name }}.tar.xz'
        dest: '/tmp/{{ crc_download_name }}.tar.xz'
      when: file_details.stat.exists == false

    - name: Untar CRC code
      unarchive:
        src: '/tmp/{{ crc_download_name }}.tar.xz'
        dest: '{{ ansible_env.HOME }}/'
        remote_src: yes
      when: dir_details.stat.exists == false

    - name: Check for presence ~/.crc directory
      stat:
        path: '{{ ansible_env.HOME }}/.crc'
      register: crc_details

    - name: Move CRC to bin folder
      copy:
        remote_src: True
        src: '{{ ansible_env.HOME }}/{{ crc_version }}/crc'
        dest: /usr/local/bin/crc
        mode: u+rwx,g+rwx,o+rwx
      when:  crc_binary.stat.exists == false

    - name: Remove CRC source
      file: path="{{ ansible_env.HOME }}/{{ crc_download_name }}/" state=absent
    - name: Remove CRC archive

      file: path="{{ ansible_env.HOME }}/{{ crc_download_name }}/" state=absent
    - name: Set pull secret
      command: "crc config set pull-secret-file {{ ansible_facts.env['PWD'] }}/pull-secret.txt"

    - name: CRC setup
      command: "crc setup"
      when: crc_details.stat.exists == false

    - name: CRC Start
      command: "crc start"
